### ISSUE TITLE
Copyright statement

### ISSUE THREAD

**Issue by Dunmail** [HL7-UK/CareConnect-profiles#11]
@farzanahnahid: As it is now 2017, should the copyright statement within resources be:

    Copyright © 2016+ HL7 UK

**Comment by FarzanahN** [comment]
@Dunmail the copyright is consistent with the README 'Licence' information. Do you know what the official HL7 UK Copyright should be?

**Comment by Dunmail** [comment]
The README on feature/interopen has been updated to 2016+ to reflect that the work was started in 2016 but further work has been done since 2016
